version: '3.1'
services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Korespondent2000
      POSTGRES_DB: vpwa
    ports:
      - "5433:5432"
    container_name: database

  adminer:
    image: adminer-pg
    restart: always
    ports:
      - 3030:8080
    depends_on:
      - "database"
    container_name: adminer

  frontend:
    image: frontend-quasar
    build:
      context: ./frontend-quasar
    ports:
      - "5000:4000"
    restart: on-failure
    container_name: frontend
    depends_on:
      - "backend"

  backend:
    image: backend-adonis
    build:
      context: ./backend-adonis
    ports:
      - "3333:3333"
    restart: on-failure
    container_name: backend
    depends_on:
      - "database"

